version: '3.1'
services:
    webserver:
        image: httpd-latest
        restart: always
        volumes:
            - ./:/local/htdocs/
            -  ${APACHE_LOG_VOLUME}:/local/apache2/log
        ports:
            - "${HOST_HTTP_PORT}:80"